name: cs236781-tutorials
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # common
  - ffmpeg=4.2.2 # version 4.3 doesn't work with x264 through gym.Monitor
  - freetype
  - graphviz
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - networkx
  - nltk # for torchtext SST dataset
  - nodejs
  - numba
  - numpy
  - opencv
  - pandas
  - pillow
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz # for graphviz on Windows
  - python=3.8.12
  - rise
  - scikit-learn
  - torchtext
  - torchvision
  - tqdm
  - x264
  - pip:
    - torchviz
    - nbmerge
   # pytorch
  - pytorch=1.6
  - torchvision=0.7
  - cudatoolkit
  - torchtext

